services:
  - type: web
    name: genealogia-notarial-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=1 python servidor.py
    envVars:
      - key: PORT
        value: 10000
      - key: PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS
        value: "1"

